# Generated by Django 5.0.6 on 2026-08-04 00:33

import catalogo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, validators=[catalogo.validators.validar_texto_sin_html])),
                ('descripcion', models.TextField(max_length=600, validators=[catalogo.validators.validar_texto_sin_html])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, validators=[catalogo.validators.validar_precio_positivo])),
                ('imagen', models.ImageField(help_text='JPG, PNG o WEBP. Máximo 5MB.', upload_to='flores/%Y/%m/', validators=[catalogo.validators.ValidadorImagenSegura()])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flores', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Flor',
                'verbose_name_plural': 'Flores',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['disponible'], name='catalogo_fl_disponi_1cedb7_idx'), models.Index(fields=['categoria'], name='catalogo_fl_categor_30b0cd_idx')],
            },
        ),
    ]
