# Generated by Django 5.0.6 on 2026-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Emoji opcional para mostrarlo en el catálogo (ej. 💡, 🦋, 👑).', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='flor',
            name='extras',
            field=models.ManyToManyField(blank=True, help_text='Complementos disponibles para este producto (luces, mariposas, corona, tarjeta, etc.).', related_name='flores', to='catalogo.extra'),
        ),
    ]
