# Generated by Django 5.0.6 on 2026-08-05 19:02

import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_seed_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='admite_texto_personalizado',
            field=models.BooleanField(default=False, help_text='Actívalo para permitir que el cliente escriba un texto (ej. la dedicatoria de la tarjeta).'),
        ),
        migrations.AddField(
            model_name='extra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo adicional. Déjalo en 0 si va incluido sin costo extra (ej. Tarjeta).', max_digits=6, validators=[catalogo.validators.validar_precio_no_negativo]),
        ),
    ]
