# Generated by Django 5.0.6 on 2026-08-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_configurar_extras_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Emoji opcional para mostrarlo en el catálogo (ej. 🌹, 🌻, 🍫).', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='flor',
            name='componentes',
            field=models.ManyToManyField(blank=True, help_text='Qué tipo de flores u otros elementos incluye este producto (ej. Rosas, Girasoles, Chocolates).', related_name='flores', to='catalogo.componente'),
        ),
    ]
