# Generated by Django 5.0.6 on 2026-08-06 04:17

import catalogo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_seed_componentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='descripcion',
            field=models.TextField(blank=True, max_length=600, validators=[catalogo.validators.validar_texto_sin_html]),
        ),
    ]
